import type { GlobalConfig } from 'payload'
import { revalidateBookingSettings } from './hooks/revalidateBookingSettings'

export const BookingSettings: GlobalConfig = {
  slug: 'booking-settings',
  label: 'Innstillinger',
  admin: {
    group: 'Booking',
  },
  access: {
    read: () => true,
  },
  hooks: {
    afterChange: [revalidateBookingSettings],
  },
  fields: [
    {
      name: 'bookingHours',
      type: 'array',
      label: 'Åpningstider for reservasjoner',
      admin: {
        description: 'Definer hvilke dager og klokkeslett man kan reservere bord',
        initCollapsed: false,
      },
      fields: [
        {
          name: 'dayOfWeek',
          type: 'select',
          label: 'Ukedag',
          required: true,
          options: [
            { label: 'Mandag', value: '1' },
            { label: 'Tirsdag', value: '2' },
            { label: 'Onsdag', value: '3' },
            { label: 'Torsdag', value: '4' },
            { label: 'Fredag', value: '5' },
            { label: 'Lørdag', value: '6' },
            { label: 'Søndag', value: '0' },
          ],
        },
        {
          name: 'openingTime',
          type: 'select',
          label: 'Åpningstid',
          required: true,
          options: [
            { label: '00:00', value: '00:00' },
            { label: '01:00', value: '01:00' },
            { label: '02:00', value: '02:00' },
            { label: '03:00', value: '03:00' },
            { label: '04:00', value: '04:00' },
            { label: '05:00', value: '05:00' },
            { label: '06:00', value: '06:00' },
            { label: '07:00', value: '07:00' },
            { label: '08:00', value: '08:00' },
            { label: '09:00', value: '09:00' },
            { label: '10:00', value: '10:00' },
            { label: '11:00', value: '11:00' },
            { label: '12:00', value: '12:00' },
            { label: '13:00', value: '13:00' },
            { label: '14:00', value: '14:00' },
            { label: '15:00', value: '15:00' },
            { label: '16:00', value: '16:00' },
            { label: '17:00', value: '17:00' },
            { label: '18:00', value: '18:00' },
            { label: '19:00', value: '19:00' },
            { label: '20:00', value: '20:00' },
            { label: '21:00', value: '21:00' },
            { label: '22:00', value: '22:00' },
            { label: '23:00', value: '23:00' },
          ],
        },
        {
          name: 'closingTime',
          type: 'select',
          label: 'Stengetid',
          required: true,
          options: [
            { label: '00:00', value: '00:00' },
            { label: '01:00', value: '01:00' },
            { label: '02:00', value: '02:00' },
            { label: '03:00', value: '03:00' },
            { label: '04:00', value: '04:00' },
            { label: '05:00', value: '05:00' },
            { label: '06:00', value: '06:00' },
            { label: '07:00', value: '07:00' },
            { label: '08:00', value: '08:00' },
            { label: '09:00', value: '09:00' },
            { label: '10:00', value: '10:00' },
            { label: '11:00', value: '11:00' },
            { label: '12:00', value: '12:00' },
            { label: '13:00', value: '13:00' },
            { label: '14:00', value: '14:00' },
            { label: '15:00', value: '15:00' },
            { label: '16:00', value: '16:00' },
            { label: '17:00', value: '17:00' },
            { label: '18:00', value: '18:00' },
            { label: '19:00', value: '19:00' },
            { label: '20:00', value: '20:00' },
            { label: '21:00', value: '21:00' },
            { label: '22:00', value: '22:00' },
            { label: '23:00', value: '23:00' },
          ],
        },
        {
          name: 'isClosed',
          type: 'checkbox',
          label: 'Stengt denne dagen',
          defaultValue: false,
          admin: {
            description: 'Kryss av hvis kafeen er stengt denne dagen',
          },
        },
      ],
    },
    {
      name: 'maxPartySize',
      type: 'number',
      label: 'Maks antall personer per reservasjon',
      defaultValue: 8,
      required: true,
      min: 1,
      admin: {
        description: 'Maksimum antall personer som kan reservere bord i en booking',
      },
    },
    {
      name: 'timeSlotDuration',
      type: 'number',
      label: 'Lengde på tidsluke (minutter)',
      defaultValue: 30,
      required: true,
      admin: {
        description: 'Hvor lenge hver tidsluke varer (f.eks. 30 eller 60 minutter)',
      },
    },
    {
      name: 'maxSeatsPerSlot',
      type: 'number',
      label: 'Maks antall seter per tidsluke',
      defaultValue: 40,
      required: true,
      min: 1,
      admin: {
        description: 'Totalt antall seter tilgjengelig per tidsluke',
      },
    },
    {
      name: 'advanceBookingDays',
      type: 'number',
      label: 'Hvor mange dager frem kan man reservere',
      defaultValue: 30,
      required: true,
      min: 1,
      max: 365,
      admin: {
        description: 'Hvor langt frem i tid kan kunder reservere bord',
      },
    },
    {
      name: 'blackoutDates',
      type: 'array',
      label: 'Stengte dager (helligdager/feriedager)',
      admin: {
        description: 'Datoer hvor det ikke er mulig å reservere bord',
      },
      fields: [
        {
          name: 'date',
          type: 'date',
          label: 'Dato',
          required: true,
          admin: {
            date: {
              pickerAppearance: 'dayOnly',
            },
          },
        },
        {
          name: 'reason',
          type: 'text',
          label: 'Grunn',
          admin: {
            description: 'F.eks. "Jul", "Påske", "Privat arrangement"',
          },
        },
      ],
    },
  ],
}
